name: CI

on:
    push:

env:
    CI: true

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                app: [react, next]
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Run tests
              run: bash __tests__/${{ matrix.app }}.sh
    send-notification:
        needs: [test]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
